### ISSUE TITLE
SKR Pro v1.2 on 230x230 Printer

### ISSUE THREAD

**Issue by JustLew3** [bgdog1/3dPrinterCase#11]
Has anyone modified the XL to 2 piece or widen the slot in Pro to accept the SKR Pro? I love this case design, but I cannot print it for my mainboard sadly.

**Comment by gulah** [comment]
I used this https://github.com/bgdog1/3dPrinterCase/blob/master/Mainboard%20Mounts%20-%20Pro%20and%20XL/Mainboard%20Mount%20Pro%20-%20SKR%20Pro%20V1.1.stl to mount an SKR PRO v1.1 in a 2 piece pro case. I believe the boards are the same dimensions? Apologies if I'm mistaken.

**Comment by bgdog1** [comment]
The XL is too big to split for printing on smaller printers. Even the display mount wont print on a smaller printer.

**Comment by bgdog1** [comment]
The Pro mounts fit the Pro and the XL cases
