### ISSUE TITLE
Request for .step files to make iterations easier

### ISSUE THREAD

**Issue by markdhooper** [bgdog1/3dPrinterCase#17]
Love the project, thank you for all of your hard work. 

I was wondering if .step files could be added in addition to .stl files.

.step files are compatible with nearly all CAD programs. 

.stl files are pretty difficult to edit, and there are some .f3d files present. Which is useless to someone without fusion360.

There are some modifications that I would like to make/versions of .stl files floating around on the Facebook group that aren't present in other form factors for myself/folks in the Facebook group. But the only thing holding me back from doing so is that the majority of these files are available only as .stl files.

Thanks again.

**Comment by bgdog1** [comment]
Step files for what components. I wont post them for them cases.

**Comment by Nathan22211** [comment]
Probably for the entire system. .step files are preferred because we can edit them in any compatible software. FreeCAD would come to mind
