### ISSUE TITLE
Request for a BTT Octopus v1.1 board

### ISSUE THREAD

**Issue by ROADwarrior82** [bgdog1/3dPrinterCase#19]
Good Afternoon, 

I just built this for my Ender 3, and it's awesome. I am about to change to an Octopus on another enclosed printer, and I would love to use this control box, but there is not an Octopus tray in the mainboard section. 

Thanks.

**Comment by jon-harper** [comment]
It will not fit in the stock case; you have to use the XL version. I am finalizing a redesigned case with the original footprint, but that's the only way to get an Octopus to fit in the stock case--the trays are not large enough.

Edit: actually, I don't think the XL has an uploaded Octopus tray, just one for the SKR Pro.

**Comment by ROADwarrior82** [comment]
Awesome. Thank you. I actually couldn't get the octopus to connect, so I ended up returning it and got a SKR 2 instead. Thank you for the response. Loving the case I am using for my Ender 3.

**Comment by bgdog1** [comment]
I found a CAD file for the Octopuss V1.1 board. I will see what I can do for a mount.
