### ISSUE TITLE
RPi Bay mount screw hole sizing 

### ISSUE THREAD

**Issue by talentedmrripley** [bgdog1/3dPrinterCase#20]
The hole size on the Pis is 2.5mm but the mounting posts seem to be setup for an M3 fastener.  You can force an M3 through the mounting holes but it's not ideal.  I have only printed and tested this with the Pi 4 mount, so perhaps it's not an issue on any of the rest.  But on the Pi 4 mount at least it should be corrected.

**Comment by bgdog1** [comment]
I drill the hole out to 3.2mm. A 2mm screw is just too small.
