### ISSUE TITLE
Case V5 and Pi mount sizing

### ISSUE THREAD

**Issue by Otann** [bgdog1/3dPrinterCase#21]
I was checking how it would look like together in Fusion 360 and that seemed off scale to me.
The holes for the screws almost match, but not quite like all other parts fit together.

Am I missing some settings or using an older version?

<img width="1654" alt="Screenshot 2022-11-23 at 02 14 13" src="https://user-images.githubusercontent.com/683786/203440028-78b69286-387b-443d-a7f9-83f78b30ffbf.png">

**Comment by truelecter** [comment]
Same for Compact Version. Quick align shows that  mount points are a bit larger than bays are
<img width="948" alt="image" src="https://user-images.githubusercontent.com/5520406/213583433-518f5a7d-7951-4b43-94cc-0bc9c39f67ee.png">

**Comment by Otann** [comment]
@truelecter I can recommend you this project that I've sound and successfully completed.
And it can be printed on a smaller printer, like Ender 3

https://github.com/jon-harper/OmniBox

**Comment by truelecter** [comment]
Thank you, that is just what I was looking for!
