### ISSUE TITLE
Request for a ender 3v2 4.2.2 / 4.2.7

### ISSUE THREAD

**Issue by drveni** [bgdog1/3dPrinterCase#22]
please for board

**Comment by bgdog1** [comment]
I think that board has the same dimensions as the 2.1 and 2.2 boards. Try printing the file Mainboard Mount V2 - Creality V2_1+.stl and see if that fits. Let me know the outcome please.

**Comment by drveni** [comment]
V2 fits!
![PXL_20230425_174441461](https://user-images.githubusercontent.com/62386210/234468107-fbb48eef-131b-4daf-a90f-df8a3ba9e033.jpg)
![Uploading PXL_20230425_174412168.jpg…]()

**Comment by bgdog1** [comment]
Thanks for the feedback. Much appreciated.
