### ISSUE TITLE
Fusion 360 Source Files?

### ISSUE THREAD

**Issue by jpflouret** [bgdog1/3dPrinterCase#4]
Great Project! I've been searching for exactly this. I'd like to print the V4 Base Standard 2 piece tall but with a different power inlet/switch (Specifically this one: https://www.amazon.ca/dp/B07S6M451F/ref=cm_sw_em_r_mt_dp_U_Lm-hFbWHF2XZX). I see there are some f3d files in the depot for some parts so I would like to modify the parts that I need and it would be so much easier to do that on the source files. If you share the source files I can share back the modified stl files.

Thanks and keep up the good work.

**Comment by bgdog1** [comment]
Done
