### ISSUE TITLE
Documentations

### ISSUE THREAD

**Issue by veskoz** [bgdog1/3dPrinterCase#6]
Hi,
First off thanks for the work you have done, i feel like there is not enough documentations on what has to be printed or which version of the case has that the others do not.. also the Case - Modular Under Table seems like just a case where u can only slide 1 piece..it's all a little bit confusing.. don't take it badly i just wanna try to help

**Comment by DanS2D** [comment]
Hi @veskoz, I think the language barrier is against us here.

I understand you see issues with the documentation.. But I can't decipher which documentation you are referring to. Are you talking about this? https://docs.coronalabs.com/api/index.html

Thank you.

**Comment by veskoz** [comment]
Hi,
I was referring to the 3dPrinterCase.
For instance i'd like to have the case under my table, but can't understand what do i have to print.
This is what i have: pi4,sk1.4turbo with wifi module, 2 mosfets, LCD12864 
I think i have to go with `https://github.com/bgdog1/3dPrinterCase/blob/master/Case%20%20-%20Modular%20Under%20Table/Under%20Table%20Mainboard%20Case%20-%20Main%20Body.stl`
But imho seems like that case can only fit one slidable piece

**Comment by DanS2D** [comment]
Ah, I see. Got mixed up there @veskoz .

I am not the author of the case. I simply forked the repo for my own use. You should take this up with the original creator.
Thank you

**Comment by JVdbKtr** [comment]
There's a PDF called 'Case_Guide V*.*.pdf" at the Facebook page linked in the Readme (https://www.facebook.com/groups/3DPrinterModding/files).
This could indeed be made more obvious.

**Comment by bgdog1** [comment]
Documentation has been moved to the Facebook Group. https://www.facebook.com/groups/3DPrinterModding
