### ISSUE TITLE
Pro V5 2pcs & standard V5 2pcs questions tops & bottoms.

### ISSUE THREAD

**Issue by craftyham** [bgdog1/3dPrinterCase#8]
Are the ProV5 2pcs bases the same hole placement & size as the standardV5 bases with the plug cut outs? I have to re print the bases. & have the main body rear pro standard V5 printed along with both pro lids and display parts. Can all the proV5 and V5 standard  2pcs parts be interchanged? I like the bases with the plug & switch.

**Comment by bgdog1** [comment]
There is a compatability chart in the guide.
